### ISSUE TITLE
Morphology map issue with paracetamol and solvent sweep

### ISSUE THREAD

**Issue by carltilbury** [bizzinho/ADDICT_Issues#14]
![morphology map error](https://cloud.githubusercontent.com/assets/16385845/13092829/e85fdb3c-d4b6-11e5-8ec2-f5a76c90eace.PNG)

Obtained an error running with paracetamol (standard CIF and MOL2 which you should have - let me know if not and I'll email to you).  The error appears when checking the morphology map (which isn't produced) and when running the solvent sweep.

Picking a single solvent (water) did calculate the morphology map without error.

**Comment by bizzinho** [comment]
I have the file and am looking into it now.

**Comment by bizzinho** [comment]
Problem is fixed, yet I'm concerned about the warning. Sent a patched version back for testing.

**Comment by carltilbury** [comment]
Still see the warning on the patched version.  Also still failed to product the map after the solvent sweep - I didn't get an error this time because I stoppe it running (I let it run for over an hour then quit it) as it was taking ages to calculate the morphology map after finishing the solvent sweep.

**Comment by bizzinho** [comment]
This is weird, it took me less than 20min on my notebook and I got no warning with PAM. Did you use the latest geometryTools folder I provided? I can send you all my files, maybe I missed some small change I made that you didn't receive?

Ps. I plan on speeding up the morphology map calc. Anyway, but for testing I left it to be recalculated always...

**Comment by carltilbury** [comment]
I think so, but why don't you send me all the files again to make sure.

**Comment by bizzinho** [comment]
Is there any update on this?

**Comment by carltilbury** [comment]
I was under the impression Jinjin was going to contact you about this - I haven't tried since last week when it didn't work for me (doing the solvent sweep and calculating the map for paracetamol).  Could you email Jinjin all the files for the version that worked for you so she can test it?

**Comment by bizzinho** [comment]
Sure thing

**Comment by carltilbury** [comment]
FYI I just ran it again with paracetamol, solvent sweep + morphology map.  I still get the sanity-check warning, but the map is calculated this time.

**Comment by bizzinho** [comment]
So weird... Was that on Matlab 2015?

**Comment by carltilbury** [comment]
Yeah 2015b.  Jinjin apparently still gets an error rather than just the warning - she's going to get in touch with you about it.

**Comment by bizzinho** [comment]
Jinjin's error was a minor thing that should be fixed by a oneliner (I sent her a suggestion what she could test)...

I am retrying PAM again on my computer... if I still don't get the warning I will install Matlab 2015b to try and see what's going on...

**Comment by bizzinho** [comment]
OK, I checked again and I am not able to reproduce the warning. I will try it out on Matlab 2015a and b.

**Comment by bizzinho** [comment]
Not reproducible on Matlab 2015a, will check b.

**Comment by bizzinho** [comment]
Hey Carl, I am not able to reproduce the warning also in Matlab 2015b... (I tried on two other people's computers)... I don't know how to proceed from here other than recommending you to delete everything you have in your (new) ADDICT folder and 'install' ADDICT from scratch...

if you have another colleague with a 2015 version you can also try and see whether he/she encounters the same problem. 

![screenshot](https://cloud.githubusercontent.com/assets/1315032/13354164/9da6fd2e-dc99-11e5-803f-e69140c11e60.jpg)

**Comment by carltilbury** [comment]
What are the implications of the warning?  The more pressing issue is probably whether Jinjin is able to run it on 2013 - last I heard she was still having issues.  Bar the warning everything seems OK for me on 2015b.

**Comment by bizzinho** [comment]
Hmm, it's a bit problematic, because it means that the morphology map doesn't satisfy the minimum sanity check I implemented... So it's not great (the map might be incorrect), though not horrible.

I have sent a new version of the code to Jinjin that should fix her issues hopefully... Hers are just compatibility problems (annotation has different syntax, etc)

**Comment by carltilbury** [comment]
Still getting the warning - map is calculated fine when I select a single solvent, it's only after the solvent sweep that the warning appears.  If you want to pursue it further maybe send me a new zip of the entire set of files (including CIF and mol2 files)?

![capture2](https://cloud.githubusercontent.com/assets/16385845/13409826/7ddf0eda-dee9-11e5-9386-be2f1a42fbc7.PNG)
![capture1](https://cloud.githubusercontent.com/assets/16385845/13409825/7ddca9f6-dee9-11e5-8aaf-afc1cfd7b8de.PNG)

**Comment by bizzinho** [comment]
Well the weird thing is that your morphology map is wrong... lol I'm running out of ideas here ^^

Let me first fix Jinjin's latest troubles and then I send you everything

**Comment by bizzinho** [comment]
cif file was the problem...
